"""Regenerate pinned Unicode 17.0 tables from local official data files."""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent.parent
DATA = Path(sys.argv[1])

def ranges(text, categories):
	result = []
	for line in text.splitlines():
		match = re.match(r"^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*(\w+)", line)
		if match and match[3] in categories:
			result.append((int(match[1], 16), int(match[2] or match[1], 16)))
	merged = []
	for start, end in sorted(result):
		if merged and start <= merged[-1][1] + 1:
			merged[-1] = (merged[-1][0], max(end, merged[-1][1]))
		else:
			merged.append((start, end))
	return merged

categories = (DATA / "DerivedGeneralCategory.txt").read_text(encoding="utf-8")
emoji = (DATA / "emoji-data.txt").read_text(encoding="utf-8")
assert "DerivedGeneralCategory-17.0.0.txt" in categories
assert "Version: 17.0" in emoji
groups = {"Letters": ranges(categories, {"Lu", "Ll", "Lt", "Lm", "Lo"}), "Marks": ranges(categories, {"Mn", "Mc", "Me"}), "Emoji": ranges(emoji, {"Emoji"})}
lines = ["// <auto-generated/>", "// Unicode 17.0.0: DerivedGeneralCategory.txt and emoji/emoji-data.txt.", "// Generated by tool/generate-unicode.py. See Unicode.LICENSE.txt.", "namespace Zongsoft.CodeAnalysis.Analyzers;", "", "internal static partial class UnicodeText", "{"]
for name, entries in groups.items():
	lines += ["\tprivate static readonly int[] _" + name.lower() + " =", "\t{"]
	values = [f"0x{start:X}, 0x{end:X}," for start, end in entries]
	lines += ["\t\t" + " ".join(values[index:index + 6]) for index in range(0, len(values), 6)]
	lines += ["\t};", ""]
lines += ["}"]
(ROOT / "src/UnicodeText.Generated.cs").write_bytes(("\r\n".join(lines) + "\r\n").encode())
print({name: len(entries) for name, entries in groups.items()})
