using System;
using System.Linq;
using System.Threading.Tasks;

using Xunit;

namespace Zongsoft.CodeAnalysis.Analyzers.Tests;

public sealed class MemberRegionTest
{
	#region 测试方法
	[Theory]
	[InlineData(9, 0)]
	[InlineData(10, 1)]
	[InlineData(11, 1)]
	public async Task ChecksCombinedMemberThreshold(int count, int expected)
	{
		var result = await AnalyzeAsync(Wrap(Members(count)));
		Assert.Equal(expected, Diagnostics(result).Length);
		Assert.Equal(expected == 0, result.Success);
		Assert.DoesNotContain("error CS", result.Output);
		if(expected > 0)
			Assert.Contains("Example.cs(5,13): error ZS2004", result.Output);
	}

	[Theory]
	[InlineData("\tpublic int this[int index] => index;\n")]
	[InlineData("\tprivate class Nested\n\t{\n\t\tpublic int Value => 0;\n\t}\n")]
	public async Task CountsIndexersAndNestedMembers(string extra)
	{
		var result = await AnalyzeAsync(Wrap(Members(9) + extra));
		Assert.Single(Diagnostics(result));
		Assert.Contains("Example.cs(5,13): error ZS2004", result.Output);
		Assert.DoesNotContain("error CS", result.Output);
	}

	[Fact]
	public async Task CountsAllTypesInFile()
	{
		var source = Wrap(Members(5)) + "\npublic class Other\n{\n" + Members(5) + "}\n";
		var result = await AnalyzeAsync(source);
		Assert.Single(Diagnostics(result));
		Assert.Contains("Example.cs(5,13): error ZS2004", result.Output);
		Assert.DoesNotContain("error CS", result.Output);
	}

	[Fact]
	public async Task ExcludesConstructorsAccessorsAndLocalFunctions()
	{
		var source = Wrap(Members(7) + "\tpublic Sample() { }\n\tpublic Sample(int value) { }\n\tpublic int Value { get; set; }\n\tpublic int Read()\n\t{\n\t\tint Local() => 0;\n\t\treturn Local();\n\t}\n");
		var result = await AnalyzeAsync(source);
		Assert.True(result.Success, result.Output);
		Assert.Empty(Diagnostics(result));
	}

	[Theory]
	[InlineData(false)]
	[InlineData(true)]
	public async Task AllowsBalancedRegionsCoveringMembers(bool nested)
	{
		var members = "\t#region First\n" + Members(5) + "\t#endregion\n\n\t#region Second\n" + Members(5, 5) + "\t#endregion\n";
		if(nested)
			members = "\t#region Outer\n" + members + "\t#endregion\n";
		var result = await AnalyzeAsync(Wrap(members));
		Assert.True(result.Success, result.Output);
		Assert.Empty(result.Output);
	}

	[Theory]
	[InlineData("\t#region Empty\n\t#endregion\n")]
	[InlineData("\t// #region Comment\n\t// #endregion\n")]
	[InlineData("\t#if NEVER\n\t#region Inactive\n\t#endregion\n\t#endif\n")]
	public async Task RejectsRegionsWithoutMemberCoverage(string region)
	{
		var result = await AnalyzeAsync(Wrap(region + Members(10)));
		Assert.Single(Diagnostics(result));
		Assert.False(result.Success, result.Output);
		Assert.DoesNotContain("error CS", result.Output);
	}

	[Fact]
	public async Task ReportsFirstUncoveredMemberAfterRegion()
	{
		var result = await AnalyzeAsync(Wrap("\t#region Covered\n" + Members(9) + "\t#endregion\n\tpublic int Uncovered => 0;\n"));
		Assert.Single(Diagnostics(result));
		Assert.Contains("Example.cs(16,13): error ZS2004", result.Output);
		Assert.DoesNotContain("error CS", result.Output);
	}

	[Fact]
	public async Task RejectsRegionsInsideMethodBodies()
	{
		var members = "\tpublic int Read()\n\t{\n\t\t#region Body\n\t\treturn 0;\n\t\t#endregion\n\t}\n\n" + Members(9);
		var result = await AnalyzeAsync(Wrap(members));
		Assert.Single(Diagnostics(result));
		Assert.Contains("Example.cs(5,13): error ZS2004", result.Output);
		Assert.DoesNotContain("error CS", result.Output);
	}

	[Theory]
	[InlineData(false, null, "warning")]
	[InlineData(true, null, "error")]
	[InlineData(true, "none", null)]
	public async Task HonorsConfiguredSeverity(bool strict, string severity, string expected)
	{
		var configuration = severity == null ? null : "root = true\n[*.cs]\nindent_style = tab\nindent_size = 4\ntab_width = 4\nend_of_line = crlf\ndotnet_diagnostic.ZS2004.severity = " + severity + "\n";
		var result = await AnalyzerRunner.AnalyzeAsync(Wrap(Members(10)), true, strict, configuration, false, false, null);
		Assert.Equal(expected == "error", !result.Success);
		if(expected == null)
			Assert.Empty(Diagnostics(result));
		else
			Assert.Contains("Example.cs(5,13): " + expected + " ZS2004", Assert.Single(Diagnostics(result)));
	}

	[Fact]
	public async Task SkipsGeneratedCode()
	{
		var result = await AnalyzeAsync("// <auto-generated/>\n" + Wrap(Members(10)));
		Assert.True(result.Success, result.Output);
		Assert.Empty(Diagnostics(result));
	}

	[Theory]
	[InlineData("true", true)]
	[InlineData("True", true)]
	[InlineData("false", false)]
	[InlineData(null, false)]
	[InlineData("invalid", false)]
	public async Task HonorsTestProjectProperty(string testProject, bool exempt)
	{
		foreach(var strict in new[] { false, true })
		{
			var result = await AnalyzerRunner.AnalyzeAsync(Wrap(Members(10)), true, strict, null, false, false, null, testProject);
			Assert.Equal(exempt || !strict, result.Success);
			if(exempt)
				Assert.Empty(result.Output);
			else
				Assert.Contains("Example.cs(5,13): " + (strict ? "error" : "warning") + " ZS2004", Assert.Single(Diagnostics(result)));

			Assert.DoesNotContain("error CS", result.Output);
		}
	}

	[Fact]
	public async Task KeepsDocumentationAndSpacingRulesInTestProjects()
	{
		var source = Wrap(Members(9) + "\t/// <summary>\n\t/// Reads a value.\n\t/// </summary>\n\tpublic int Read(int value)\n\t{\n\t\tif(value < 0)\n\t\t{\n\t\t\treturn 0;\n\t\t}\n\t\twhile(value > 0)\n\t\t\tvalue--;\n\t\treturn value;\n\t}\n");
		var result = await AnalyzerRunner.AnalyzeAsync(source, true, true, null, false, false, null, "true");
		Assert.Empty(Diagnostics(result));
		Assert.False(result.Success, result.Output);
		foreach(var id in new[] { "ZS2003", "ZS3001", "ZS3002", "ZS3003" })
			Assert.Single(result.Output.Split('\n'), line => line.Contains("error " + id + ":", StringComparison.Ordinal));

		Assert.DoesNotContain("error CS", result.Output);
	}
	#endregion

	#region 辅助方法
	private static string Members(int count, int start = 0) => string.Concat(Enumerable.Range(start, count)
		.Select(index => "\tpublic int " + (index % 2 == 0 ? "Property" + index : "Method" + index + "()") + " => 0;\n"));
	private static string Wrap(string members) => "namespace Samples;\n\npublic class Sample\n{\n" + members + "}\n";
	private static string[] Diagnostics(AnalysisResult result) => result.Output.Split('\n').Where(line => line.Contains(" ZS2004:", StringComparison.Ordinal)).ToArray();
	private static Task<AnalysisResult> AnalyzeAsync(string source) => AnalyzerRunner.AnalyzeAsync(source, true, true, null, false, false, null);
	#endregion
}
